// Comprehensive Indian Cities & Local Bank Branches Directory

export const INDIAN_CITIES = [
  { id: 'chennai', name: 'Chennai', state: 'Tamil Nadu', count: 18 },
  { id: 'mumbai', name: 'Mumbai', state: 'Maharashtra', count: 18 },
  { id: 'bengaluru', name: 'Bengaluru', state: 'Karnataka', count: 18 },
  { id: 'delhi', name: 'Delhi NCR', state: 'Delhi', count: 18 },
  { id: 'hyderabad', name: 'Hyderabad', state: 'Telangana', count: 18 },
  { id: 'coimbatore', name: 'Coimbatore', state: 'Tamil Nadu', count: 16 },
  { id: 'madurai', name: 'Madurai', state: 'Tamil Nadu', count: 15 },
  { id: 'trichy', name: 'Trichy (Tiruchirappalli)', state: 'Tamil Nadu', count: 15 },
  { id: 'kochi', name: 'Kochi (Cochin)', state: 'Kerala', count: 16 },
  { id: 'kolkata', name: 'Kolkata', state: 'West Bengal', count: 17 },
  { id: 'pune', name: 'Pune', state: 'Maharashtra', count: 17 },
  { id: 'ahmedabad', name: 'Ahmedabad', state: 'Gujarat', count: 16 },
  { id: 'jaipur', name: 'Jaipur', state: 'Rajasthan', count: 15 },
  { id: 'lucknow', name: 'Lucknow', state: 'Uttar Pradesh', count: 15 },
  { id: 'chandigarh', name: 'Chandigarh', state: 'Punjab/Haryana', count: 15 },
  { id: 'indore', name: 'Indore', state: 'Madhya Pradesh', count: 15 },
  { id: 'surat', name: 'Surat', state: 'Gujarat', count: 15 },
  { id: 'vizag', name: 'Visakhapatnam', state: 'Andhra Pradesh', count: 15 },
];

export const CITY_BRANCHES = {
  chennai: [
    { id: 'chn_anna_nagar', name: 'Anna Nagar Branch', area: 'Anna Nagar 2nd Avenue', pin: '600040', ifsc: 'LOCA0004001' },
    { id: 'chn_t_nagar', name: 'T. Nagar Commercial Branch', area: 'Usman Road, T. Nagar', pin: '600017', ifsc: 'LOCA0004002' },
    { id: 'chn_adyar', name: 'Adyar Main Branch', area: 'Lattice Bridge Road, Adyar', pin: '600020', ifsc: 'LOCA0004003' },
    { id: 'chn_velachery', name: 'Velachery Tech Corridor Branch', area: '100 Feet Bypass Road', pin: '600042', ifsc: 'LOCA0004004' },
    { id: 'chn_mylapore', name: 'Mylapore Heritage Branch', area: 'Luz Church Road, Mylapore', pin: '600004', ifsc: 'LOCA0004005' },
    { id: 'chn_nungambakkam', name: 'Nungambakkam High Road Branch', area: 'NH Road, Nungambakkam', pin: '600034', ifsc: 'LOCA0004006' },
    { id: 'chn_porur', name: 'Porur Junction Branch', area: 'Mount Poonamallee Road', pin: '600116', ifsc: 'LOCA0004007' },
    { id: 'chn_tambaram', name: 'Tambaram Sanatorium Branch', area: 'GST Road, Tambaram', pin: '600045', ifsc: 'LOCA0004008' },
    { id: 'chn_ambattur', name: 'Ambattur Industrial Estate Branch', area: 'Ambattur OT', pin: '600058', ifsc: 'LOCA0004009' },
    { id: 'chn_chromepet', name: 'Chromepet Main Branch', area: 'GST Road, Chromepet', pin: '600044', ifsc: 'LOCA0004010' },
    { id: 'chn_guindy', name: 'Guindy Tech Park Hub', area: 'Mount Road, Guindy', pin: '600032', ifsc: 'LOCA0004011' },
    { id: 'chn_kilpauk', name: 'Kilpauk Garden Branch', area: 'Kilpauk Garden Road', pin: '600010', ifsc: 'LOCA0004012' },
    { id: 'chn_ashok_nagar', name: 'Ashok Nagar Pillar Branch', area: '1st Block, Ashok Nagar', pin: '600083', ifsc: 'LOCA0004013' },
    { id: 'chn_vadapalani', name: 'Vadapalani Metro Branch', area: 'Arcot Road, Vadapalani', pin: '600026', ifsc: 'LOCA0004014' },
    { id: 'chn_omr', name: 'OMR Sholinganallur IT Branch', area: 'Rajiv Gandhi Salai (OMR)', pin: '600119', ifsc: 'LOCA0004015' },
    { id: 'chn_egmore', name: 'Egmore Station Hub', area: 'Gandhi Irwin Road, Egmore', pin: '600008', ifsc: 'LOCA0004016' },
    { id: 'chn_royapettah', name: 'Royapettah High Road Branch', area: 'Royapettah', pin: '600014', ifsc: 'LOCA0004017' },
    { id: 'chn_kodambakkam', name: 'Kodambakkam Trustpuram Branch', area: 'Arcot Road', pin: '600024', ifsc: 'LOCA0004018' },
  ],

  mumbai: [
    { id: 'mum_bkc', name: 'BKC Financial Center Hub', area: 'Bandra Kurla Complex', pin: '400051', ifsc: 'LOCA0001001' },
    { id: 'mum_nariman', name: 'Nariman Point Flagship', area: 'Maker Chambers, Nariman Point', pin: '400021', ifsc: 'LOCA0001002' },
    { id: 'mum_andheri_w', name: 'Andheri West Link Road Branch', area: 'Lokhandwala, Andheri W', pin: '400053', ifsc: 'LOCA0001003' },
    { id: 'mum_andheri_e', name: 'Andheri East MIDC Hub', area: 'MIDC Industrial Area', pin: '400093', ifsc: 'LOCA0001004' },
    { id: 'mum_borivali', name: 'Borivali West Station Branch', area: 'LT Road, Borivali W', pin: '400092', ifsc: 'LOCA0001005' },
    { id: 'mum_powai', name: 'Powai Hiranandani Branch', area: 'Central Avenue, Powai', pin: '400076', ifsc: 'LOCA0001006' },
    { id: 'mum_thane', name: 'Thane Majiwada Hub', area: 'Eastern Express Highway, Thane', pin: '400601', ifsc: 'LOCA0001007' },
    { id: 'mum_navi_mumbai', name: 'Vashi Sector 17 Branch', area: 'Vashi, Navi Mumbai', pin: '400703', ifsc: 'LOCA0001008' },
    { id: 'mum_dadar', name: 'Dadar TT Circle Branch', area: 'Dadar West', pin: '400028', ifsc: 'LOCA0001009' },
    { id: 'mum_juhu', name: 'Juhu Scheme VIP Branch', area: 'JVPD Scheme, Juhu', pin: '400049', ifsc: 'LOCA0001010' },
    { id: 'mum_ghatkopar', name: 'Ghatkopar East MG Road', area: 'Ghatkopar East', pin: '400077', ifsc: 'LOCA0001011' },
    { id: 'mum_malad', name: 'Malad Mindspace IT Hub', area: 'Mindspace, Malad W', pin: '400064', ifsc: 'LOCA0001012' },
    { id: 'mum_chembur', name: 'Chembur Diamond Garden Branch', area: 'Chembur East', pin: '400071', ifsc: 'LOCA0001013' },
    { id: 'mum_lower_parel', name: 'Lower Parel Mill Compound', area: 'Senapati Bapat Marg', pin: '400013', ifsc: 'LOCA0001014' },
    { id: 'mum_worli', name: 'Worli Sea Face Branch', area: 'Worli', pin: '400030', ifsc: 'LOCA0001015' },
    { id: 'mum_kandivali', name: 'Kandivali East Thakur Village', area: 'Thakur Village', pin: '400101', ifsc: 'LOCA0001016' },
    { id: 'mum_goregaon', name: 'Goregaon East Nesco Hub', area: 'Western Express Highway', pin: '400063', ifsc: 'LOCA0001017' },
    { id: 'mum_mulund', name: 'Mulund West LBS Marg', area: 'LBS Marg, Mulund W', pin: '400080', ifsc: 'LOCA0001018' },
  ],

  bengaluru: [
    { id: 'blr_mg_road', name: 'MG Road Flagship Hub', area: 'MG Road, Trinity Circle', pin: '560001', ifsc: 'LOCA0002001' },
    { id: 'blr_indiranagar', name: 'Indiranagar 100ft Road Branch', area: '12th Main, Indiranagar', pin: '560038', ifsc: 'LOCA0002002' },
    { id: 'blr_koramangala', name: 'Koramangala 80ft Road Branch', area: '4th Block, Koramangala', pin: '560034', ifsc: 'LOCA0002003' },
    { id: 'blr_whitefield', name: 'Whitefield ITPL Hub', area: 'ITPL Main Road, Whitefield', pin: '560066', ifsc: 'LOCA0002004' },
    { id: 'blr_hsr_layout', name: 'HSR Layout Sector 1 Branch', area: '27th Main, HSR Layout', pin: '560102', ifsc: 'LOCA0002005' },
    { id: 'blr_electronic_city', name: 'Electronic City Phase 1 Hub', area: 'Hosur Road, E-City', pin: '560100', ifsc: 'LOCA0002006' },
    { id: 'blr_jayanagar', name: 'Jayanagar 4th Block Branch', area: '11th Main, Jayanagar', pin: '560011', ifsc: 'LOCA0002007' },
    { id: 'blr_malleshwaram', name: 'Malleshwaram Sampige Road', area: 'Sampige Road', pin: '560003', ifsc: 'LOCA0002008' },
    { id: 'blr_marathahalli', name: 'Marathahalli Outer Ring Road', area: 'ORR Junction', pin: '560037', ifsc: 'LOCA0002009' },
    { id: 'blr_bellandur', name: 'Bellandur EcoSpace Hub', area: 'Outer Ring Road, Bellandur', pin: '560103', ifsc: 'LOCA0002010' },
    { id: 'blr_banashankari', name: 'Banashankari 3rd Stage', area: '100ft Ring Road', pin: '560085', ifsc: 'LOCA0002011' },
    { id: 'blr_hebbal', name: 'Hebbal Manyata Tech Park Hub', area: 'Manyata Tech Park', pin: '560045', ifsc: 'LOCA0002012' },
    { id: 'blr_rajajinagar', name: 'Rajajinagar 1st Block', area: 'Dr. Rajkumar Road', pin: '560010', ifsc: 'LOCA0002013' },
    { id: 'blr_yelahanka', name: 'Yelahanka New Town Hub', area: 'Major Unnikrishnan Road', pin: '560064', ifsc: 'LOCA0002014' },
    { id: 'blr_sarjapur', name: 'Sarjapur Road Wipro Hub', area: 'Sarjapur Main Road', pin: '560035', ifsc: 'LOCA0002015' },
    { id: 'blr_basavanagudi', name: 'Basavanagudi DVG Road', area: 'DVG Road, Basavanagudi', pin: '560004', ifsc: 'LOCA0002016' },
    { id: 'blr_kammanahalli', name: 'Kammanahalli Main Road', area: 'HRBR Layout', pin: '560084', ifsc: 'LOCA0002017' },
    { id: 'blr_btm_layout', name: 'BTM Layout 2nd Stage', area: 'Outer Ring Road, BTM', pin: '560076', ifsc: 'LOCA0002018' },
  ],

  delhi: [
    { id: 'del_cp', name: 'Connaught Place Main Flagship', area: 'Inner Circle, CP', pin: '110001', ifsc: 'LOCA0003001' },
    { id: 'del_gurgaon_cyber', name: 'Gurugram Cyber City Hub', area: 'DLF Cyber City, Phase 2', pin: '122002', ifsc: 'LOCA0003002' },
    { id: 'del_noida_sector18', name: 'Noida Sector 18 Commercial Hub', area: 'Sector 18, Noida', pin: '201301', ifsc: 'LOCA0003003' },
    { id: 'del_south_ext', name: 'South Extension Part 2', area: 'South Ext 2', pin: '110049', ifsc: 'LOCA0003004' },
    { id: 'del_dwarka', name: 'Dwarka Sector 12 Metro Hub', area: 'Sector 12, Dwarka', pin: '110075', ifsc: 'LOCA0003005' },
    { id: 'del_nehru_place', name: 'Nehru Place Financial Center', area: 'Nehru Place', pin: '110019', ifsc: 'LOCA0003006' },
    { id: 'del_lajpat_nagar', name: 'Lajpat Nagar Central Market', area: 'Lajpat Nagar 2', pin: '110024', ifsc: 'LOCA0003007' },
    { id: 'del_rohini', name: 'Rohini Sector 7 Metro Branch', area: 'Sector 7, Rohini', pin: '110085', ifsc: 'LOCA0003008' },
    { id: 'del_janakpuri', name: 'Janakpuri District Centre', area: 'Janakpuri West', pin: '110058', ifsc: 'LOCA0003009' },
    { id: 'del_vasant_kunj', name: 'Vasant Kunj Nelson Mandela Road', area: 'Vasant Kunj Phase 2', pin: '110070', ifsc: 'LOCA0003010' },
    { id: 'del_pitampura', name: 'Pitampura TV Tower Branch', area: 'Netaji Subhash Place', pin: '110034', ifsc: 'LOCA0003011' },
    { id: 'del_karol_bagh', name: 'Karol Bagh Ajmal Khan Road', area: 'Karol Bagh', pin: '110005', ifsc: 'LOCA0003012' },
    { id: 'del_faridabad', name: 'Faridabad Sector 16 Hub', area: 'Sector 16, Faridabad', pin: '121002', ifsc: 'LOCA0003013' },
    { id: 'del_ghaziabad', name: 'Ghaziabad RDC Raj Nagar', area: 'RDC, Raj Nagar', pin: '201002', ifsc: 'LOCA0003014' },
    { id: 'del_greater_noida', name: 'Greater Noida Pari Chowk Hub', area: 'Knowledge Park II', pin: '201310', ifsc: 'LOCA0003015' },
    { id: 'del_gurgaon_golf_course', name: 'Gurugram Golf Course Road', area: 'Sector 54, Gurugram', pin: '122003', ifsc: 'LOCA0003016' },
    { id: 'del_saket', name: 'Saket District Centre Hub', area: 'Press Enclave Road', pin: '110017', ifsc: 'LOCA0003017' },
    { id: 'del_mayur_vihar', name: 'Mayur Vihar Phase 1 Branch', area: 'Mayur Vihar', pin: '110091', ifsc: 'LOCA0003018' },
  ],

  hyderabad: [
    { id: 'hyd_hitec', name: 'HITEC City Cyber Towers Hub', area: 'HITEC City Phase 1', pin: '500081', ifsc: 'LOCA0005001' },
    { id: 'hyd_banjara_hills', name: 'Banjara Hills Road No 12', area: 'Banjara Hills', pin: '500034', ifsc: 'LOCA0005002' },
    { id: 'hyd_gachibowli', name: 'Gachibowli Financial District Hub', area: 'Nanakramguda', pin: '500032', ifsc: 'LOCA0005003' },
    { id: 'hyd_jubilee_hills', name: 'Jubilee Hills Road No 36', area: 'Jubilee Hills', pin: '500033', ifsc: 'LOCA0005004' },
    { id: 'hyd_madhapur', name: 'Madhapur Metro Branch', area: 'Main Road, Madhapur', pin: '500081', ifsc: 'LOCA0005005' },
    { id: 'hyd_secunderabad', name: 'Secunderabad MG Road Branch', area: 'Park Lane, Secunderabad', pin: '500003', ifsc: 'LOCA0005006' },
    { id: 'hyd_kukatpally', name: 'Kukatpally KPHB Colony', area: 'KPHB Main Road', pin: '500072', ifsc: 'LOCA0005007' },
    { id: 'hyd_begumpet', name: 'Begumpet Airport Plaza', area: 'Begumpet Road', pin: '500016', ifsc: 'LOCA0005008' },
    { id: 'hyd_ameerpet', name: 'Ameerpet Metro Junction', area: 'Ameerpet Cross Roads', pin: '500038', ifsc: 'LOCA0005009' },
    { id: 'hyd_somajiguda', name: 'Somajiguda Raj Bhavan Road', area: 'Somajiguda', pin: '500082', ifsc: 'LOCA0005010' },
    { id: 'hyd_kondapur', name: 'Kondapur RTO Junction', area: 'Kondapur Main Road', pin: '500084', ifsc: 'LOCA0005011' },
    { id: 'hyd_miyapur', name: 'Miyapur Metro Terminal', area: 'Miyapur Main Road', pin: '500049', ifsc: 'LOCA0005012' },
    { id: 'hyd_dilsukhnagar', name: 'Dilsukhnagar Main Road', area: 'Dilsukhnagar', pin: '500060', ifsc: 'LOCA0005013' },
    { id: 'hyd_himayatnagar', name: 'Himayatnagar Main Road', area: 'Himayatnagar', pin: '500029', ifsc: 'LOCA0005014' },
    { id: 'hyd_uppal', name: 'Uppal Ring Road Hub', area: 'Uppal Main Road', pin: '500039', ifsc: 'LOCA0005015' },
    { id: 'hyd_lb_nagar', name: 'LB Nagar X Roads', area: 'LB Nagar', pin: '500074', ifsc: 'LOCA0005016' },
    { id: 'hyd_manikonda', name: 'Manikonda Lanco Hills Road', area: 'Manikonda', pin: '500089', ifsc: 'LOCA0005017' },
    { id: 'hyd_shamshabad', name: 'Shamshabad Airport Zone', area: 'RGIA Airport Road', pin: '501218', ifsc: 'LOCA0005018' },
  ],

  coimbatore: [
    { id: 'cbe_avinashi_road', name: 'Avinashi Road Flagship Branch', area: 'Avinashi Road, Peelamedu', pin: '641004', ifsc: 'LOCA0008001' },
    { id: 'cbe_rs_puram', name: 'RS Puram DB Road Branch', area: 'DB Road, RS Puram', pin: '641002', ifsc: 'LOCA0008002' },
    { id: 'cbe_gandhipuram', name: 'Gandhipuram Cross Cut Road', area: 'Cross Cut Road', pin: '641012', ifsc: 'LOCA0008003' },
    { id: 'cbe_saibaba_colony', name: 'Saibaba Colony NSR Road', area: 'NSR Road', pin: '641011', ifsc: 'LOCA0008004' },
    { id: 'cbe_saravanampatti', name: 'Saravanampatti IT Park Hub', area: 'Sathy Road, Saravanampatti', pin: '641035', ifsc: 'LOCA0008005' },
    { id: 'cbe_singanallur', name: 'Singanallur Trichy Road', area: 'Trichy Road', pin: '641005', ifsc: 'LOCA0008006' },
    { id: 'cbe_ramanathapuram', name: 'Ramanathapuram Junction', area: 'Trichy Road', pin: '641045', ifsc: 'LOCA0008007' },
    { id: 'cbe_thudiyalur', name: 'Thudiyalur Mettupalayam Road', area: 'MTP Road', pin: '641034', ifsc: 'LOCA0008008' },
    { id: 'cbe_ukkadam', name: 'Ukkadam Town Hall Branch', area: 'Town Hall', pin: '641001', ifsc: 'LOCA0008009' },
    { id: 'cbe_vadamadurai', name: 'Vadamadurai Kurudampalayam', area: 'MTP Road', pin: '641017', ifsc: 'LOCA0008010' },
    { id: 'cbe_race_course', name: 'Race Course VIP Branch', area: 'Race Course Road', pin: '641018', ifsc: 'LOCA0008011' },
    { id: 'cbe_hope_college', name: 'Hope College Peelamedu', area: 'Avinashi Road', pin: '641014', ifsc: 'LOCA0008012' },
    { id: 'cbe_ganapathy', name: 'Ganapathy Sathy Road', area: 'Ganapathy Bus Stand', pin: '641006', ifsc: 'LOCA0008013' },
    { id: 'cbe_kuniamuthur', name: 'Kuniamuthur Palakkad Road', area: 'Palakkad Road', pin: '641008', ifsc: 'LOCA0008014' },
    { id: 'cbe_sundarapuram', name: 'Sundarapuram Pollachi Road', area: 'Pollachi Main Road', pin: '641024', ifsc: 'LOCA0008015' },
    { id: 'cbe_sulur', name: 'Sulur Airforce Station Zone', area: 'Trichy Road, Sulur', pin: '641402', ifsc: 'LOCA0008016' },
  ],

  madurai: [
    { id: 'mdu_kk_nagar', name: 'KK Nagar Main Branch', area: '80 Feet Road, KK Nagar', pin: '625020', ifsc: 'LOCA0009001' },
    { id: 'mdu_anna_nagar', name: 'Anna Nagar 80ft Road Branch', area: 'Anna Nagar Main Road', pin: '625020', ifsc: 'LOCA0009002' },
    { id: 'mdu_simmakkal', name: 'Simmakkal Heritage Branch', area: 'North Veli Street', pin: '625001', ifsc: 'LOCA0009003' },
    { id: 'mdu_periyar', name: 'Periyar Bus Stand Branch', area: 'West Veli Street', pin: '625001', ifsc: 'LOCA0009004' },
    { id: 'mdu_tvs_nagar', name: 'TVS Nagar Subramaniapuram', area: 'TVS Nagar', pin: '625003', ifsc: 'LOCA0009005' },
    { id: 'mdu_ss_colony', name: 'SS Colony Bypass Road', area: 'Bypass Road, SS Colony', pin: '625016', ifsc: 'LOCA0009006' },
    { id: 'mdu_tallakulam', name: 'Tallakulam Gokhale Road', area: 'Gokhale Road', pin: '625002', ifsc: 'LOCA0009007' },
    { id: 'mdu_k_pudur', name: 'K. Pudur Alagar Kovil Road', area: 'Alagar Kovil Main Road', pin: '625007', ifsc: 'LOCA0009008' },
    { id: 'mdu_pasumalai', name: 'Pasumalai TPU College Zone', area: 'Pasumalai', pin: '625004', ifsc: 'LOCA0009009' },
    { id: 'mdu_thirunagar', name: 'Thirunagar 1st Stop Branch', area: 'GST Road, Thirunagar', pin: '625006', ifsc: 'LOCA0009010' },
    { id: 'mdu_sellur', name: 'Sellur 50ft Road Branch', area: 'Sellur Main Road', pin: '625002', ifsc: 'LOCA0009011' },
    { id: 'mdu_villapuram', name: 'Villapuram Aruppukottai Road', area: 'Villapuram', pin: '625012', ifsc: 'LOCA0009012' },
    { id: 'mdu_mattuthavani', name: 'Mattuthavani Integrated Bus Hub', area: 'KK Nagar Extension', pin: '625007', ifsc: 'LOCA0009013' },
    { id: 'mdu_aarapalayam', name: 'Aarapalayam Cross Road', area: 'Aarapalayam', pin: '625016', ifsc: 'LOCA0009014' },
    { id: 'mdu_uthangudi', name: 'Uthangudi High Court Bench Zone', area: 'Ring Road', pin: '625107', ifsc: 'LOCA0009015' },
  ],

  trichy: [
    { id: 'try_cantonment', name: 'Cantonment Flagship Branch', area: 'Collectorate Road, Cantonment', pin: '620001', ifsc: 'LOCA0010001' },
    { id: 'try_thillai_nagar', name: 'Thillai Nagar Main Branch', area: '11th Cross, Thillai Nagar', pin: '620018', ifsc: 'LOCA0010002' },
    { id: 'try_srirangam', name: 'Srirangam Temple Street', area: 'Gandhi Road, Srirangam', pin: '620006', ifsc: 'LOCA0010003' },
    { id: 'try_kk_nagar', name: 'KK Nagar Sundar Nagar Hub', area: 'KK Nagar Main Road', pin: '620021', ifsc: 'LOCA0010004' },
    { id: 'try_bhel', name: 'BHEL Kailasapuram Township Zone', area: 'BHEL Township', pin: '620014', ifsc: 'LOCA0010005' },
    { id: 'try_chatram', name: 'Chatram Bus Stand Branch', area: 'Main Guard Gate', pin: '620002', ifsc: 'LOCA0010006' },
    { id: 'try_palakkarai', name: 'Palakkarai Station Road', area: 'Palakkarai', pin: '620001', ifsc: 'LOCA0010007' },
    { id: 'try_tennur', name: 'Tennur High Road Branch', area: 'Tennur Main Road', pin: '620017', ifsc: 'LOCA0010008' },
    { id: 'try_woraiyur', name: 'Woraiyur Salai Road Branch', area: 'Salai Road, Woraiyur', pin: '620003', ifsc: 'LOCA0010009' },
    { id: 'try_nit_thuvakudi', name: 'Thuvakudi NIT Tech Campus', area: 'Tanjore Highway', pin: '620015', ifsc: 'LOCA0010010' },
    { id: 'try_lalgudi', name: 'Lalgudi Main Road Branch', area: 'Lalgudi', pin: '621601', ifsc: 'LOCA0010011' },
    { id: 'try_manapparai', name: 'Manapparai Bus Stand Zone', area: 'Manapparai', pin: '621306', ifsc: 'LOCA0010012' },
    { id: 'try_karumandapam', name: 'Karumandapam Dindigul Road', area: 'Dindigul Road', pin: '620001', ifsc: 'LOCA0010013' },
    { id: 'try_kathanathapuram', name: 'Kattur Oil Mill Branch', area: 'Tanjore Road, Kattur', pin: '620019', ifsc: 'LOCA0010014' },
    { id: 'try_no1_tolgate', name: 'No. 1 Tolgate Samayapuram Zone', area: 'Trichy Chennai Highway', pin: '621216', ifsc: 'LOCA0010015' },
  ],

  kochi: [
    { id: 'koc_mg_road', name: 'MG Road Ernakulam Flagship', area: 'MG Road, Jos Junction', pin: '682016', ifsc: 'LOCA0011001' },
    { id: 'koc_kakkanad', name: 'Kakkanad Infopark IT Hub', area: 'Infopark Expressway', pin: '682030', ifsc: 'LOCA0011002' },
    { id: 'koc_edappally', name: 'Edappally Lulu Mall Zone', area: 'Bypass Junction, Edappally', pin: '682024', ifsc: 'LOCA0011003' },
    { id: 'koc_marine_drive', name: 'Marine Drive Waterfront Branch', area: 'Shanmugham Road', pin: '682031', ifsc: 'LOCA0011004' },
    { id: 'koc_kaloor', name: 'Kaloor Stadium Junction', area: 'Deshabhimani Road', pin: '682017', ifsc: 'LOCA0011005' },
    { id: 'koc_vytilla', name: 'Vyttila Mobility Hub Branch', area: 'Vyttila Junction', pin: '682019', ifsc: 'LOCA0011006' },
    { id: 'koc_fort_kochi', name: 'Fort Kochi Heritage Branch', area: 'KB Jacob Road', pin: '682001', ifsc: 'LOCA0011007' },
    { id: 'koc_aluva', name: 'Aluva Bank Junction Branch', area: 'Railway Station Road', pin: '683101', ifsc: 'LOCA0011008' },
    { id: 'koc_tripunithura', name: 'Tripunithura Statue Junction', area: 'Statue Junction', pin: '682301', ifsc: 'LOCA0011009' },
    { id: 'koc_angamaly', name: 'Angamaly CIAL Airport Zone', area: 'NH 544, Angamaly', pin: '683572', ifsc: 'LOCA0011010' },
    { id: 'koc_palarivattom', name: 'Palarivattom Pipeline Junction', area: 'Civil Line Road', pin: '682025', ifsc: 'LOCA0011011' },
    { id: 'koc_panampilly', name: 'Panampilly Nagar VIP Zone', area: 'Main Avenue', pin: '682036', ifsc: 'LOCA0011012' },
    { id: 'koc_kadavanthra', name: 'Kadavanthra Junction Branch', area: 'KP Vallon Road', pin: '682020', ifsc: 'LOCA0011013' },
    { id: 'koc_mattancherry', name: 'Mattancherry Bazar Branch', area: 'Gujarati Road', pin: '682002', ifsc: 'LOCA0011014' },
    { id: 'koc_kalamassery', name: 'Kalamassery CUSAT Campus Hub', area: 'CUSAT Road', pin: '682022', ifsc: 'LOCA0011015' },
    { id: 'koc_perumbavoor', name: 'Perumbavoor AM Road Branch', area: 'MC Road', pin: '683542', ifsc: 'LOCA0011016' },
  ],

  kolkata: [
    { id: 'kol_park_street', name: 'Park Street Central Flagship', area: 'Park Street', pin: '700016', ifsc: 'LOCA0006001' },
    { id: 'kol_salt_lake', name: 'Salt Lake Sector 5 IT Hub', area: 'Sector V, Salt Lake', pin: '700091', ifsc: 'LOCA0006002' },
    { id: 'kol_new_town', name: 'New Town Action Area 1', area: 'Major Arterial Road', pin: '700156', ifsc: 'LOCA0006003' },
    { id: 'kol_dalhousie', name: 'BBD Bagh Commercial Hub', area: 'Dalhousie Square', pin: '700001', ifsc: 'LOCA0006004' },
    { id: 'kol_gariahat', name: 'Gariahat South Market', area: 'Gariahat Road', pin: '700019', ifsc: 'LOCA0006005' },
    { id: 'kol_alipore', name: 'Alipore VIP Avenue Branch', area: 'Judge Court Road', pin: '700027', ifsc: 'LOCA0006006' },
    { id: 'kol_dum_dum', name: 'Dum Dum Airport Zone', area: 'Jessore Road', pin: '700052', ifsc: 'LOCA0006007' },
    { id: 'kol_howrah', name: 'Howrah Station Road Branch', area: 'Foreshore Road', pin: '711101', ifsc: 'LOCA0006008' },
    { id: 'kol_behala', name: 'Behala Chowrasta Branch', area: 'Diamond Harbour Road', pin: '700034', ifsc: 'LOCA0006009' },
    { id: 'kol_shambazar', name: 'Shambazar 5-Point Crossing', area: 'Bidhan Sarani', pin: '700004', ifsc: 'LOCA0006010' },
    { id: 'kol_tollygunge', name: 'Tollygunge Metro Station Branch', area: 'Deshapran Sasmal Road', pin: '700033', ifsc: 'LOCA0006011' },
    { id: 'kol_jadavpur', name: 'Jadavpur 8B Bus Stand Hub', area: 'Raja SC Mullick Road', pin: '700032', ifsc: 'LOCA0006012' },
    { id: 'kol_ballygunge', name: 'Ballygunge Circular Road', area: 'Ballygunge Phari', pin: '700019', ifsc: 'LOCA0006013' },
    { id: 'kol_kasba', name: 'Kasba Ruby Hospital Zone', area: 'EM Bypass, Kasba', pin: '700107', ifsc: 'LOCA0006014' },
    { id: 'kol_kamalgazi', name: 'Garia Kamalgazi Bypass', area: 'NSC Bose Road', pin: '700103', ifsc: 'LOCA0006015' },
    { id: 'kol_laketown', name: 'Lake Town VIP Road Clock Tower', area: 'VIP Road', pin: '700089', ifsc: 'LOCA0006016' },
    { id: 'kol_sinthee', name: 'Sinthee More BT Road', area: 'BT Road', pin: '700050', ifsc: 'LOCA0006017' },
  ],

  pune: [
    { id: 'pun_mg_road', name: 'Camp MG Road Flagship', area: 'MG Road, Camp', pin: '411001', ifsc: 'LOCA0007001' },
    { id: 'pun_hinjewadi', name: 'Hinjawadi Rajiv Gandhi IT Hub', area: 'Phase 1, Hinjawadi', pin: '411057', ifsc: 'LOCA0007002' },
    { id: 'pun_viman_nagar', name: 'Viman Nagar Phoenix Hub', area: 'Nagar Road, Viman Nagar', pin: '411014', ifsc: 'LOCA0007003' },
    { id: 'pun_kothrud', name: 'Kothrud Paud Road Branch', area: 'Paud Road, Kothrud', pin: '411038', ifsc: 'LOCA0007004' },
    { id: 'pun_baner', name: 'Baner High Street Hub', area: 'Baner-Pashan Link Road', pin: '411045', ifsc: 'LOCA0007005' },
    { id: 'pun_wakad', name: 'Wakad Datta Mandir Road', area: 'Wakad Main Road', pin: '411057', ifsc: 'LOCA0007006' },
    { id: 'pun_shivajinagar', name: 'Shivajinagar FC Road Branch', area: 'Fergusson College Road', pin: '411004', ifsc: 'LOCA0007007' },
    { id: 'pun_hadapsar', name: 'Hadapsar Magarpatta Cybercity', area: 'Magarpatta City', pin: '411028', ifsc: 'LOCA0007008' },
    { id: 'pun_pimpri', name: 'Pimpri Chinchwad Industrial Hub', area: 'Old Mumbai-Pune Highway', pin: '411018', ifsc: 'LOCA0007009' },
    { id: 'pun_swargate', name: 'Swargate Tilak Road Branch', area: 'Tilak Road', pin: '411002', ifsc: 'LOCA0007010' },
    { id: 'pun_kharadi', name: 'Kharadi EON Free Zone Hub', area: 'EON IT Park, Kharadi', pin: '411014', ifsc: 'LOCA0007011' },
    { id: 'pun_aunde', name: 'Aundh ITI Road Branch', area: 'ITI Road, Aundh', pin: '411007', ifsc: 'LOCA0007012' },
    { id: 'pun_pimple_saudagar', name: 'Pimple Saudagar Govind Garden', area: 'Kunal Icon Road', pin: '411027', ifsc: 'LOCA0007013' },
    { id: 'pun_katraj', name: 'Katraj Bharati Vidyapeeth Zone', area: 'Satara Road', pin: '411046', ifsc: 'LOCA0007014' },
    { id: 'pun_kalyani_nagar', name: 'Kalyani Nagar East Avenue', area: 'East Avenue', pin: '411006', ifsc: 'LOCA0007015' },
    { id: 'pun_nibm', name: 'NIBM Undri Kondhwa Hub', area: 'NIBM Road', pin: '411048', ifsc: 'LOCA0007016' },
    { id: 'pun_bavdhan', name: 'Bavdhan Chandani Chowk Zone', area: 'Mumbai-Bangalore Highway', pin: '411021', ifsc: 'LOCA0007017' },
  ],
};

// Fallback generator for other cities so all 18+ cities display 15+ branches cleanly
const generateCityBranches = (cityName, cityCode, prefixIfsc) => {
  const localities = [
    'Main Commercial Hub', 'Station Road Branch', 'Civil Lines Hub', 'MG Road Center',
    'Industrial Area Phase 1', 'Ring Road Junction', 'Town Hall Square', 'VIP Colony Branch',
    'Tech Park Corridor', 'Market Complex', 'Central Bus Stand Zone', 'College Road Branch',
    'High Court Zone', 'Airport Road Branch', 'Bypass Road Hub'
  ];
  return localities.map((loc, idx) => ({
    id: `${cityCode}_${idx + 1}`,
    name: `${cityName} ${loc}`,
    area: `${loc}, ${cityName}`,
    pin: `${prefixIfsc.slice(-3)}${100 + idx}`,
    ifsc: `${prefixIfsc}0${10 + idx}`,
  }));
};

INDIAN_CITIES.forEach((c) => {
  if (!CITY_BRANCHES[c.id]) {
    CITY_BRANCHES[c.id] = generateCityBranches(c.name, c.id, `LOCA00${c.id.length}00`);
  }
});

export const getBranchesForCity = (cityId) => {
  return CITY_BRANCHES[cityId] || CITY_BRANCHES['chennai'];
};
